#!/usr/bin/env python3
"""Regenerates Sources/AgentIcons.swift from Assets/AgentIcons/*.png.

Each brand is a set of pixel-exact PNGs named <kind>@<scale>x.png
(scale 2/3/4 = 36/54/72px rasterizations of the 18pt sidebar icon
slot). The build produces a single swiftc binary with no resource
bundle, so the PNGs are embedded as base64 and assembled into an
18pt NSImage with one NSBitmapImageRep per scale — the backing store
maps 1:1, no resampling.

Sources for the glyphs: tty7's curated agent icons
(tty7/assets/icons/agents — official marks, normalized to
a 24x24 box with a #FF0000 placeholder fill that is re-blacked before
rasterizing), plus qwen/kimi/cline from Simple Icons. To refresh a
glyph, drop new PNGs into the assets dir and rebuild.
"""

import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "Assets" / "AgentIcons"
TARGET = ROOT / "Sources" / "Core" / "Agents" / "AgentIcons.swift"

def is_monochrome(png: Path) -> bool:
    """True when every opaque pixel is grayscale (a tintable mask)."""
    try:
        from PIL import Image
    except ImportError:
        return False
    with Image.open(png) as im:
        im = im.convert("RGBA")
        for r, g, b, a in im.getdata():
            if a > 16 and max(r, g, b) - min(r, g, b) > 12:
                return False
    return True


def main() -> None:
    kinds: dict[str, dict[int, str]] = {}
    masks: set[str] = set()
    for png in sorted(ASSETS.glob("*.png")):
        stem = png.stem  # kind@2x
        kind, _, scale = stem.rpartition("@")
        if not scale.endswith("x"):
            raise SystemExit(f"unrecognized asset name: {png.name}")
        kinds.setdefault(kind, {})[int(scale[:-1])] = base64.b64encode(png.read_bytes()).decode()
        # A pure monochrome glyph (all opaque pixels grayscale) is an
        # alpha MASK: rendered as template so the host can tint it (white
        # on a dark sidebar). Colored marks keep their native palette.
        if kind not in masks and is_monochrome(png):
            masks.add(kind)

    rows = []
    for kind in sorted(kinds):
        scales = kinds[kind]
        missing = [s for s in (2, 3, 4) if s not in scales]
        if missing:
            raise SystemExit(f"{kind}: missing {missing}x scales")
        inner = ", ".join(f'{sc}: "{scales[sc]}"' for sc in (2, 3, 4))
        rows.append(f'        "{kind}": [{inner}],')
    if not rows:
        raise SystemExit(f"no assets found in {ASSETS}")

    table = "\n".join(rows)
    mask_list = ", ".join(f'"{k}"' for k in sorted(masks))
    swift = f'''import AppKit

/// GENERATED by tools/gen_agent_icons.py — do not edit by hand.
/// Regenerate: python3 tools/gen_agent_icons.py (or just build).

enum AgentBrandIcons {{
    static let pngs: [String: [Int: String]] = [
{table}
    ]

    /// Brands whose glyph is a pure monochrome mask (black lines +
    /// alpha): rendered as template so the host tints them — white on a
    /// dark sidebar. Everything else keeps its native palette.
    static let maskKinds: Set<String> = [{mask_list}]

    /// 18pt image with one pixel-exact rep per display scale; the
    /// sidebar slot maps 1:1 onto the backing store, no resampling.
    static func image(for kind: String?) -> NSImage? {{
        guard let key = kind?.lowercased(), !key.isEmpty,
              let scales = pngs[key] else {{ return nil }}
        let image = NSImage(size: NSSize(width: 18, height: 18))
        for (_, b64) in scales.sorted(by: {{ $0.key < $1.key }}) {{
            guard let data = Data(base64Encoded: b64),
                  let rep = NSBitmapImageRep(data: data) else {{ continue }}
            rep.size = NSSize(width: 18, height: 18)
            image.addRepresentation(rep)
        }}
        image.isTemplate = maskKinds.contains(key)
        return image
    }}
}}
'''
    TARGET.write_text(swift)
    print(f"AgentIcons.swift: {len(kinds)} brands "
          f"({len(masks)} tintable masks), {sum(len(s) for s in kinds.values())} scales")


if __name__ == "__main__":
    main()
