// goty — see CLAUDE.md for the working principles.
//
// GENERATED FILE — do not edit by hand. Regenerate with:
//   python3 tools/convert-agent-manifests.py > Sources/Core/AgentManifests.swift
//
// Passive agent-state rules ported 1:1 from goty's detection manifests
// (upstream-manifests). Upstream versions:
//   claude, claude-code <- claude.toml 2026.08.13.1
//   codex     <- codex.toml 2026.08.09.1
//   pi        <- pi.toml 2026.06.10.1
//   opencode  <- opencode.toml 2026.06.10.1
//   gemini    <- gemini.toml 2026.06.10.1
//   grok      <- grok.toml 2026.07.16.2
//   copilot   <- github-copilot.toml 2026.07.07.1
//   droid     <- droid.toml 2026.06.10.1

/// Rules per AgentCatalog command key. Evaluated by AgentDetect.
let agentManifestTable: [String: [AgentManifestRule]] = [
        "claude": [
            AgentManifestRule(id: "osc_title_working", state: .working, priority: 1100, region: "osc_title", visibleWorking: true, gate: AgentMatchGate(regex: ["^[\\x{2800}-\\x{28FF}\\x{25D0}-\\x{25D3}] "])),
            AgentManifestRule(id: "btw_overlay_working", state: .working, priority: 975, region: "bottom_non_empty_lines(5)", visibleWorking: true, gate: AgentMatchGate(lineRegex: ["^\\s*/btw(?:\\s|$)", "(?i)esc to close\\s*$"])),
            AgentManifestRule(id: "transcript_viewer", state: .unknown, priority: 1000, region: "bottom_non_empty_lines(3)", skipStateUpdate: true, gate: AgentMatchGate(contains: ["showing detailed transcript"], any: [AgentMatchGate(contains: ["ctrl+o", "to toggle"]), AgentMatchGate(contains: ["ctrl+e", "show all"]), AgentMatchGate(contains: ["ctrl+e", "collapse"]), AgentMatchGate(contains: ["↑↓ scroll"]), AgentMatchGate(contains: ["? for shortcuts"])])),
            AgentManifestRule(id: "live_blocked_form", state: .blocked, priority: 980, region: "after_last_horizontal_rule", visibleBlocker: true, gate: AgentMatchGate(contains: ["esc to cancel"], any: [AgentMatchGate(contains: ["enter to confirm"]), AgentMatchGate(contains: ["enter to select"], any: [AgentMatchGate(contains: ["tab/arrow keys to navigate"]), AgentMatchGate(contains: ["arrow keys to navigate"]), AgentMatchGate(contains: ["arrows to navigate"]), AgentMatchGate(contains: ["↑/↓ to navigate"]), AgentMatchGate(contains: ["↑↓ to navigate"])])])),
            AgentManifestRule(id: "dynamic_workflow_prompt", state: .blocked, priority: 980, region: "whole_recent", visibleBlocker: true, gate: AgentMatchGate(contains: ["run a dynamic workflow?", "esc to cancel"])),
            AgentManifestRule(id: "live_prompt_box", state: .idle, priority: 950, region: "prompt_box_body", visibleIdle: true, gate: AgentMatchGate(lineRegex: ["^\\s*❯"], not: [AgentMatchGate(contains: ["enter to select"]), AgentMatchGate(contains: ["esc to cancel"]), AgentMatchGate(contains: ["tab/arrow keys"]), AgentMatchGate(contains: ["arrow keys to navigate"]), AgentMatchGate(contains: ["↑/↓ to navigate"])])),
            AgentManifestRule(id: "model_picker_menu", state: .unknown, priority: 900, region: "whole_recent", skipStateUpdate: true, gate: AgentMatchGate(contains: ["select model", "enter to set as default", "esc to cancel"], not: [AgentMatchGate(contains: ["do you want to proceed?"]), AgentMatchGate(contains: ["enter to select"])])),
            AgentManifestRule(id: "bash_permission_prompt", state: .blocked, priority: 850, region: "whole_recent", visibleBlocker: true, gate: AgentMatchGate(contains: ["do you want to proceed?"], all: [AgentMatchGate(any: [AgentMatchGate(lineRegex: ["(?i)^\\s*❯?\\s*yes\\b"]), AgentMatchGate(lineRegex: ["(?i)^\\s*1\\.\\s*yes\\b"]), AgentMatchGate(lineRegex: ["(?i)^\\s*2\\.\\s*no\\b"])])], any: [AgentMatchGate(contains: ["bash command"]), AgentMatchGate(contains: ["bash("]), AgentMatchGate(contains: ["contains expansion"]), AgentMatchGate(contains: ["tab to amend"]), AgentMatchGate(contains: ["ctrl+e to explain"])])),
            AgentManifestRule(id: "generic_permission_prompt", state: .blocked, priority: 840, region: "after_last_horizontal_rule", visibleBlocker: true, gate: AgentMatchGate(contains: ["do you want to proceed?", "esc to cancel"], all: [AgentMatchGate(any: [AgentMatchGate(lineRegex: ["(?i)^\\s*❯?\\s*1\\.\\s*yes\\b"]), AgentMatchGate(lineRegex: ["(?i)^\\s*2\\.\\s*yes\\b"]), AgentMatchGate(lineRegex: ["(?i)^\\s*2\\.\\s*no\\b"]), AgentMatchGate(lineRegex: ["(?i)^\\s*3\\.\\s*no\\b"])])])),
            AgentManifestRule(id: "legacy_no_prompt_blocker", state: .blocked, priority: 300, region: "whole_recent", gate: AgentMatchGate(any: [AgentMatchGate(contains: ["do you want to"], any: [AgentMatchGate(contains: ["yes"]), AgentMatchGate(contains: ["❯"])]), AgentMatchGate(contains: ["would you like to"], any: [AgentMatchGate(contains: ["yes"]), AgentMatchGate(contains: ["❯"])]), AgentMatchGate(contains: ["waiting for permission"]), AgentMatchGate(contains: ["do you want to allow this connection?"]), AgentMatchGate(contains: ["tab to amend"]), AgentMatchGate(contains: ["ctrl+e to explain"]), AgentMatchGate(contains: ["do you want to proceed?", "esc to cancel"]), AgentMatchGate(contains: ["review your answers"]), AgentMatchGate(contains: ["skip interview and plan immediately"])], not: [AgentMatchGate(regex: ["(?m)^\\s*❯\\s*$"])])),
            AgentManifestRule(id: "osc_title_idle", state: .idle, priority: 250, region: "osc_title", visibleIdle: true, gate: AgentMatchGate(regex: ["^\\x{2733} "])),
            AgentManifestRule(id: "osc_progress_idle", state: .idle, priority: 250, region: "osc_progress", gate: AgentMatchGate(regex: ["^4;0"])),
        ],
        "claude-code": [
            AgentManifestRule(id: "osc_title_working", state: .working, priority: 1100, region: "osc_title", visibleWorking: true, gate: AgentMatchGate(regex: ["^[\\x{2800}-\\x{28FF}\\x{25D0}-\\x{25D3}] "])),
            AgentManifestRule(id: "btw_overlay_working", state: .working, priority: 975, region: "bottom_non_empty_lines(5)", visibleWorking: true, gate: AgentMatchGate(lineRegex: ["^\\s*/btw(?:\\s|$)", "(?i)esc to close\\s*$"])),
            AgentManifestRule(id: "transcript_viewer", state: .unknown, priority: 1000, region: "bottom_non_empty_lines(3)", skipStateUpdate: true, gate: AgentMatchGate(contains: ["showing detailed transcript"], any: [AgentMatchGate(contains: ["ctrl+o", "to toggle"]), AgentMatchGate(contains: ["ctrl+e", "show all"]), AgentMatchGate(contains: ["ctrl+e", "collapse"]), AgentMatchGate(contains: ["↑↓ scroll"]), AgentMatchGate(contains: ["? for shortcuts"])])),
            AgentManifestRule(id: "live_blocked_form", state: .blocked, priority: 980, region: "after_last_horizontal_rule", visibleBlocker: true, gate: AgentMatchGate(contains: ["esc to cancel"], any: [AgentMatchGate(contains: ["enter to confirm"]), AgentMatchGate(contains: ["enter to select"], any: [AgentMatchGate(contains: ["tab/arrow keys to navigate"]), AgentMatchGate(contains: ["arrow keys to navigate"]), AgentMatchGate(contains: ["arrows to navigate"]), AgentMatchGate(contains: ["↑/↓ to navigate"]), AgentMatchGate(contains: ["↑↓ to navigate"])])])),
            AgentManifestRule(id: "dynamic_workflow_prompt", state: .blocked, priority: 980, region: "whole_recent", visibleBlocker: true, gate: AgentMatchGate(contains: ["run a dynamic workflow?", "esc to cancel"])),
            AgentManifestRule(id: "live_prompt_box", state: .idle, priority: 950, region: "prompt_box_body", visibleIdle: true, gate: AgentMatchGate(lineRegex: ["^\\s*❯"], not: [AgentMatchGate(contains: ["enter to select"]), AgentMatchGate(contains: ["esc to cancel"]), AgentMatchGate(contains: ["tab/arrow keys"]), AgentMatchGate(contains: ["arrow keys to navigate"]), AgentMatchGate(contains: ["↑/↓ to navigate"])])),
            AgentManifestRule(id: "model_picker_menu", state: .unknown, priority: 900, region: "whole_recent", skipStateUpdate: true, gate: AgentMatchGate(contains: ["select model", "enter to set as default", "esc to cancel"], not: [AgentMatchGate(contains: ["do you want to proceed?"]), AgentMatchGate(contains: ["enter to select"])])),
            AgentManifestRule(id: "bash_permission_prompt", state: .blocked, priority: 850, region: "whole_recent", visibleBlocker: true, gate: AgentMatchGate(contains: ["do you want to proceed?"], all: [AgentMatchGate(any: [AgentMatchGate(lineRegex: ["(?i)^\\s*❯?\\s*yes\\b"]), AgentMatchGate(lineRegex: ["(?i)^\\s*1\\.\\s*yes\\b"]), AgentMatchGate(lineRegex: ["(?i)^\\s*2\\.\\s*no\\b"])])], any: [AgentMatchGate(contains: ["bash command"]), AgentMatchGate(contains: ["bash("]), AgentMatchGate(contains: ["contains expansion"]), AgentMatchGate(contains: ["tab to amend"]), AgentMatchGate(contains: ["ctrl+e to explain"])])),
            AgentManifestRule(id: "generic_permission_prompt", state: .blocked, priority: 840, region: "after_last_horizontal_rule", visibleBlocker: true, gate: AgentMatchGate(contains: ["do you want to proceed?", "esc to cancel"], all: [AgentMatchGate(any: [AgentMatchGate(lineRegex: ["(?i)^\\s*❯?\\s*1\\.\\s*yes\\b"]), AgentMatchGate(lineRegex: ["(?i)^\\s*2\\.\\s*yes\\b"]), AgentMatchGate(lineRegex: ["(?i)^\\s*2\\.\\s*no\\b"]), AgentMatchGate(lineRegex: ["(?i)^\\s*3\\.\\s*no\\b"])])])),
            AgentManifestRule(id: "legacy_no_prompt_blocker", state: .blocked, priority: 300, region: "whole_recent", gate: AgentMatchGate(any: [AgentMatchGate(contains: ["do you want to"], any: [AgentMatchGate(contains: ["yes"]), AgentMatchGate(contains: ["❯"])]), AgentMatchGate(contains: ["would you like to"], any: [AgentMatchGate(contains: ["yes"]), AgentMatchGate(contains: ["❯"])]), AgentMatchGate(contains: ["waiting for permission"]), AgentMatchGate(contains: ["do you want to allow this connection?"]), AgentMatchGate(contains: ["tab to amend"]), AgentMatchGate(contains: ["ctrl+e to explain"]), AgentMatchGate(contains: ["do you want to proceed?", "esc to cancel"]), AgentMatchGate(contains: ["review your answers"]), AgentMatchGate(contains: ["skip interview and plan immediately"])], not: [AgentMatchGate(regex: ["(?m)^\\s*❯\\s*$"])])),
            AgentManifestRule(id: "osc_title_idle", state: .idle, priority: 250, region: "osc_title", visibleIdle: true, gate: AgentMatchGate(regex: ["^\\x{2733} "])),
            AgentManifestRule(id: "osc_progress_idle", state: .idle, priority: 250, region: "osc_progress", gate: AgentMatchGate(regex: ["^4;0"])),
        ],
        "codex": [
            AgentManifestRule(id: "osc_title_blocked", state: .blocked, priority: 1100, region: "osc_title", visibleBlocker: true, gate: AgentMatchGate(contains: ["Action Required"])),
            AgentManifestRule(id: "osc_title_working", state: .working, priority: 1050, region: "osc_title", visibleWorking: true, gate: AgentMatchGate(regex: ["(?:^| )[⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏](?: |$)"])),
            AgentManifestRule(id: "transcript_viewer", state: .unknown, priority: 1000, region: "after_last_prompt_marker", skipStateUpdate: true, gate: AgentMatchGate(contains: ["↑/↓ to scroll", "pgup/pgdn to", "home/end to jump", "q to quit"], any: [AgentMatchGate(contains: ["esc to edit prev"]), AgentMatchGate(contains: ["esc/← to edit prev"])])),
            AgentManifestRule(id: "trust_directory", state: .blocked, priority: 950, region: "top_non_empty_lines(20)", visibleBlocker: true, gate: AgentMatchGate(all: [AgentMatchGate(regex: ["\\A> You are in [^\\r\\n]+(?:\\r?\\n|$)"]), AgentMatchGate(regex: ["(?s)Do\\s+you\\s+trust\\s+the\\s+contents\\s+of\\s+this\\s+directory\\?"])])),
            AgentManifestRule(id: "live_strong_blocker", state: .blocked, priority: 900, region: "after_last_prompt_marker", visibleBlocker: true, gate: AgentMatchGate(any: [AgentMatchGate(contains: ["press enter to confirm or esc to cancel"]), AgentMatchGate(contains: ["enter to submit answer"]), AgentMatchGate(contains: ["enter to submit all"]), AgentMatchGate(contains: ["allow command?"])])),
            AgentManifestRule(id: "weak_blocker", state: .blocked, priority: 600, region: "whole_recent", gate: AgentMatchGate(any: [AgentMatchGate(contains: ["[y/n]"]), AgentMatchGate(contains: ["yes (y)"]), AgentMatchGate(contains: ["do you want to"], any: [AgentMatchGate(contains: ["yes"]), AgentMatchGate(contains: ["❯"])]), AgentMatchGate(contains: ["would you like to"], any: [AgentMatchGate(contains: ["yes"]), AgentMatchGate(contains: ["❯"])])])),
            AgentManifestRule(id: "screen_working_fallback", state: .working, priority: 500, region: "bottom_non_empty_lines(3)", visibleWorking: true, gate: AgentMatchGate(lineRegex: ["^[•◦]\\s+Working \\([^)]*esc to interrupt\\)(?: · .*)?$"], not: [AgentMatchGate(contains: ["■ Conversation interrupted"])])),
            AgentManifestRule(id: "osc_title_idle", state: .idle, priority: 100, region: "osc_title", visibleIdle: true, gate: AgentMatchGate(regex: ["\\S"], not: [AgentMatchGate(regex: ["(?:^| )[⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏](?: |$)"]), AgentMatchGate(contains: ["Action Required"])])),
        ],
        "pi": [
            AgentManifestRule(id: "working_literal", state: .working, priority: 100, region: "whole_recent", visibleWorking: true, gate: AgentMatchGate(contains: ["Working..."])),
        ],
        "opencode": [
            AgentManifestRule(id: "permission_required", state: .blocked, priority: 300, region: "whole_recent", visibleBlocker: true, gate: AgentMatchGate(any: [AgentMatchGate(contains: ["△ Permission required"]), AgentMatchGate(contains: ["esc dismiss"], all: [AgentMatchGate(any: [AgentMatchGate(contains: ["↑↓ select"]), AgentMatchGate(contains: ["⇆ tab"])])], any: [AgentMatchGate(contains: ["enter confirm"]), AgentMatchGate(contains: ["enter submit"]), AgentMatchGate(contains: ["enter toggle"])])])),
            AgentManifestRule(id: "interrupt_hint_working", state: .working, priority: 110, region: "whole_recent", visibleWorking: true, gate: AgentMatchGate(any: [AgentMatchGate(contains: ["esc to interrupt"]), AgentMatchGate(contains: ["ctrl+c to interrupt"]), AgentMatchGate(contains: ["press esc to interrupt"]), AgentMatchGate(lineRegex: ["(?i).*opencode.*esc (again to )?interrupt"])])),
            AgentManifestRule(id: "progress_bar_working", state: .working, priority: 100, region: "whole_recent", visibleWorking: true, gate: AgentMatchGate(regex: ["(■|⬝){4,}"])),
        ],
        "gemini": [
            AgentManifestRule(id: "apply_or_allow_change", state: .blocked, priority: 300, region: "whole_recent", visibleBlocker: true, gate: AgentMatchGate(any: [AgentMatchGate(contains: ["│ Apply this change"]), AgentMatchGate(contains: ["│ Allow execution"]), AgentMatchGate(all: [AgentMatchGate(contains: ["yes"]), AgentMatchGate(any: [AgentMatchGate(contains: ["waiting for user confirmation"]), AgentMatchGate(contains: ["│ Do you want to proceed"]), AgentMatchGate(contains: ["do you want to proceed?"])])]), AgentMatchGate(lineRegex: ["(?i)^\\s*❯.*(yes|allow)"])])),
            AgentManifestRule(id: "esc_cancel_working", state: .working, priority: 100, region: "whole_recent", visibleWorking: true, gate: AgentMatchGate(contains: ["esc to cancel"])),
        ],
        "grok": [
            AgentManifestRule(id: "osc_title_blocked", state: .blocked, priority: 1300, region: "osc_title", visibleBlocker: true, gate: AgentMatchGate(contains: ["Action Required"])),
            AgentManifestRule(id: "option_dialog_blocked", state: .blocked, priority: 1200, region: "whole_recent", visibleBlocker: true, gate: AgentMatchGate(lineRegex: ["^\\s*┃\\s+[0-9a-z]+\\s+\\([●○]\\)\\s"])),
            AgentManifestRule(id: "permission_hints_blocked", state: .blocked, priority: 1190, region: "bottom_non_empty_lines(2)", visibleBlocker: true, gate: AgentMatchGate(contains: [":select", "ctrl+o:yolo", "ctrl+c:cancel"])),
            AgentManifestRule(id: "question_dialog_hints_blocked", state: .blocked, priority: 1185, region: "bottom_non_empty_lines(2)", visibleBlocker: true, gate: AgentMatchGate(contains: ["tab:scrollback", "shift+x:dismiss"])),
            AgentManifestRule(id: "permission_scope_selector", state: .blocked, priority: 1180, region: "whole_recent", visibleBlocker: true, gate: AgentMatchGate(contains: ["yes, proceed", "no, reject"], any: [AgentMatchGate(contains: ["use ← → to choose permission whitelist scope"]), AgentMatchGate(contains: ["←/→:scope"])])),
            AgentManifestRule(id: "background_work_chip_working", state: .working, priority: 1170, region: "top_non_empty_lines(1)", visibleWorking: true, gate: AgentMatchGate(lineRegex: ["[⋅:⸬⁙.·]\\s+[1-9][0-9]*\\s+│"])),
            AgentManifestRule(id: "osc_progress_working", state: .working, priority: 1150, region: "osc_progress", visibleWorking: true, gate: AgentMatchGate(regex: ["^4;1;-1$"])),
            AgentManifestRule(id: "osc_title_idle", state: .idle, priority: 1100, region: "osc_title", visibleIdle: true, gate: AgentMatchGate(regex: ["(?:^| - )grok$"], not: [AgentMatchGate(regex: ["[\\x{2800}-\\x{28FF}]"])])),
            AgentManifestRule(id: "osc_title_working", state: .working, priority: 1000, region: "osc_title", visibleWorking: true, gate: AgentMatchGate(regex: ["\\S"])),
            AgentManifestRule(id: "osc_progress_idle", state: .idle, priority: 950, region: "osc_progress", visibleIdle: true, gate: AgentMatchGate(regex: ["^4;0;0$"])),
            AgentManifestRule(id: "spinner_status_working", state: .working, priority: 200, region: "whole_recent", visibleWorking: true, gate: AgentMatchGate(lineRegex: ["^\\s*[\\x{2801}-\\x{28FF}]\\s.*\\[stop\\]\\s*$"])),
            AgentManifestRule(id: "esc_cancel_hints_working", state: .working, priority: 190, region: "bottom_non_empty_lines(2)", visibleWorking: true, gate: AgentMatchGate(contains: ["esc:cancel", "ctrl+.:shortcuts"])),
            AgentManifestRule(id: "waiting_tool_working", state: .working, priority: 120, region: "whole_recent", visibleWorking: true, gate: AgentMatchGate(any: [AgentMatchGate(all: [AgentMatchGate(contains: ["ctrl+c:cancel", "ctrl+enter:interject"]), AgentMatchGate(contains: ["waiting"])]), AgentMatchGate(lineRegex: ["^\\s*[\\x{2801}-\\x{28FF}]\\s+(Run|Read|Search|List)\\b"])])),
            AgentManifestRule(id: "prompt_hints_idle", state: .idle, priority: 100, region: "bottom_non_empty_lines(2)", visibleIdle: true, gate: AgentMatchGate(contains: ["ctrl+.:shortcuts"], not: [AgentMatchGate(contains: ["esc:cancel"]), AgentMatchGate(contains: ["ctrl+c:cancel"])])),
        ],
        "copilot": [
            AgentManifestRule(id: "selection_blocker", state: .blocked, priority: 300, region: "whole_recent", visibleBlocker: true, gate: AgentMatchGate(all: [AgentMatchGate(any: [AgentMatchGate(contains: ["esc to cancel"]), AgentMatchGate(contains: ["esc cancel"])]), AgentMatchGate(any: [AgentMatchGate(contains: ["enter to select"]), AgentMatchGate(contains: ["enter to confirm"]), AgentMatchGate(contains: ["enter to submit"]), AgentMatchGate(contains: ["enter accept"])])])),
            AgentManifestRule(id: "working_cancel_hint", state: .working, priority: 100, region: "whole_recent", visibleWorking: true, gate: AgentMatchGate(any: [AgentMatchGate(contains: ["esc to cancel"]), AgentMatchGate(contains: ["esc cancel"]), AgentMatchGate(contains: ["esc again to cancel"]), AgentMatchGate(contains: ["esc interrupt"])])),
        ],
        "droid": [
            AgentManifestRule(id: "execute_selection_blocker", state: .blocked, priority: 300, region: "whole_recent", visibleBlocker: true, gate: AgentMatchGate(contains: ["enter to select", "esc to cancel"], all: [AgentMatchGate(any: [AgentMatchGate(contains: ["> yes, allow"]), AgentMatchGate(contains: ["> no, cancel"])])], any: [AgentMatchGate(contains: ["↑↓ to navigate"]), AgentMatchGate(contains: ["use ↑↓ to navigate"])])),
            AgentManifestRule(id: "selection_menu_blocker", state: .blocked, priority: 290, region: "bottom_non_empty_lines(8)", visibleBlocker: true, gate: AgentMatchGate(contains: ["enter select", "esc cancel"], any: [AgentMatchGate(contains: ["↑/↓ navigate"]), AgentMatchGate(contains: ["↑↓ navigate"])])),
            AgentManifestRule(id: "spinner_stop_working", state: .working, priority: 110, region: "whole_recent", visibleWorking: true, gate: AgentMatchGate(contains: ["esc to stop"], lineRegex: ["^\\s*[\\u2800-\\u28FF]"])),
            AgentManifestRule(id: "stop_hint_working", state: .working, priority: 100, region: "whole_recent", visibleWorking: true, gate: AgentMatchGate(contains: ["esc to stop"])),
        ]
]

/// goty agents that have no passive manifest here (omp, aider, …)
/// degrade to the known-agent idle fallback — badge only, no live state.
