/* Minimal static-build export header (normally generated by CMake).
 * We compile cmark-gfm straight into the app binary: no exports. */
#ifndef CMARK_GFM_EXPORT_H
#define CMARK_INLINE inline
#define CMARK_GFM_EXPORT_H
#define CMARK_INLINE inline
#define CMARK_GFM_EXPORT
#define CMARK_EXPORT
#define CMARK_INLINE inline
#define CMARK_GFM_EXPORT
#define CMARK_EXPORT_NO_EXPORT
#define CMARK_DEPRECATED(x)
#define CMARK_DEPRECATED_EXPORT(x)
#define CMARK_DEPRECATED_NO_EXPORT(x)
#endif
